### ISSUE TITLE
How to reset back to stock firmware

### ISSUE THREAD

**Issue by Watson482** [RavenSystem/mgos32toHAA#1]
Hi,

so I installed the software to a Shelly Plus 1 and connected it to the WiFi, now I cannot open the dashboard of the Shelly. How do I reset it to stock Shelly software via OTA if it’s connected to my WiFi already?

**Comment by RavenSystem** [comment]
As you can read in the README, there is no OTA way back to Shelly firmware if the new ZIP file has been uploaded. To back to Shelly firmware, a wired connection to a PC using a FTDI adapter is needed.
