### ISSUE TITLE
OTA update on Shelly Plus 1 with Tasmota?

### ISSUE THREAD

**Issue by zonehun** [RavenSystem/mgos32toHAA#2]
Can I update my Tasmota flashed (14.0.0) Shelly Plus 1 with this method? Tasmota also have an OTA update possibility where I'm able to set any URL.

**Comment by RavenSystem** [comment]
No with this. But there is other method for your case. Check Tasmota to HAA: https://github.com/RavenSystem/esp-homekit-devices/wiki/installation#third-party-installation-tools
